project:
  type: website
  
website:
  title: "BdlP-2023"
  description: |
    Website para Biología de las Plantas (Laboratorio) de la Universidad de Antioquia, 2023-1
  site-url: https://alexespinosaco.github.io/biologia-plantas
  repo-url: https://github.com/alexespinosaco/biologia-plantas
  #page-navigation: true
  page-footer: 
    center: "[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.es), [Álex Espinosa-Correa](http://alexespinosaco.github.io/), 2023"

  open-graph: true
  twitter-card: 
    creator: "@alexespinosaco"
    card-style: summary_large_image
  google-analytics: 
    tracking-id: "G-JYJJ0L4H6K"
    anonymize-ip: true

  sidebar: 
    subtitle: "Laboratorio"
    style: docked
    logo: images/bldp.png
    search: true
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/alexespinosaco/biologia-plantas
    contents: 
      - href: index.qmd
        text: Inicio
      - href: https://alexespinosaco.github.io/biologia-plantas-manual/
        text: Manual de laboratorio
      - section: "Presentaciones"
        contents: 
          - href: presentaciones/histologia-I.qmd
          - href: presentaciones/histologia-II.qmd
          - href: presentaciones/diversidad.qmd
          - href: presentaciones/raiz.qmd

link-external-icon: false
link-external-newwindow: true
date-format: iso
csl: apa.csl
crossref: 
  fig-title: Fig

format: 
  html: 
   theme: 
     light: flaty
     dark: darkly
   toc: true
