project:
  type: website
  
website:
  title: "Biología de las Plantas: laboratorio"
  sidebar: 
    style: docked
    search: true
    contents: 
      - href: https://alexespinosaco.github.io/manual-laboratorio-biologia-plantas/
        text: Manual de laboratorio
      - index.qmd
      - presentaciones/histologia-I.qmd


  page-navigation: false
    
link-external-icon: false
link-external-newwindow: true
date-format: iso
csl: apa.csl

format: 
  html: 
   theme: minty
   toc: true
   link-external-icon: true
   link-external-newwindow: true